import type { HassEntity } from "./hass";
import type { T } from "./i18n";

// Default English names/options of the integration's entities, translated in the
// panel. A name the user changed in Home Assistant is shown as-is.
export const ENTITY_TEXT: ReadonlySet<string> = new Set(/* i18n */ [
  "Abort OTA",
  "Alerts only",
  "App presence",
  "Auto-dock on error",
  "Back up map",
  "Camera light",
  "Camera light off now",
  "Cancel task",
  "Charging handbrake",
  "Clear all zones & channels",
  "Dock and forget progress",
  "Exit remote control",
  "Factory reset",
  "Find my robot (play sound)",
  "Find robot beep",
  "Finish zone recording",
  "Force stop",
  "Geofence radius",
  "Live cut height",
  "Live cut speed",
  "Live move speed",
  "Lock",
  "Mobile notifications",
  "Mowing pattern",
  "Prefer 4G",
  "RTK auto-pause",
  "RTK diagnostics",
  "RTK pause threshold",
  "Rainy mowing",
  "Re-advertise Bluetooth",
  "Recharge & resume",
  "Recharge threshold",
  "Reset charging station",
  "Restore backup map",
  "Resume threshold",
  "Return-to-dock route",
  "Self-check",
  "Set charging station here",
  "Sync timezone",
  "Theft detection",
  "Theft lock",
  "Toggle LTE airplane mode",
  "Vehicle LED",
  "Voice language",
  "Volume",
  "Zone order",
  "Off",
  "Low",
  "Medium",
  "High",
  "Custom",
  "Direct route",
  "Follow perimeter",
  "Optimize",
  "Zigzag",
  "Adaptive zigzag",
  "Chessboard",
  "Perimeter laps only",
  "English",
  "French-Canadian",
  "French-France",
  "German",
  "Italian",
  "Spanish",
  // Sensor names (Diagnostics).
  "Anti-theft lock",
  "Backup maps",
  "Blade firmware",
  "Bluetooth name",
  "Bluetooth signal",
  "Camera AE gear",
  "Cellular IP",
  "Device locked",
  "Error code",
  "Firmware version",
  "GNSS satellites",
  "IP address",
  "L1 SNR",
  "L1 satellites",
  "L2 SNR",
  "L2 satellites",
  "L5 SNR",
  "L5 satellites",
  "LTE link",
  "LTE signal",
  "Last mow battery used",
  "Last mow completion",
  "Last mow details",
  "Last mow duration",
  "Last mow session",
  "Last reply opcode",
  "Latest map backup",
  "Lens heater fires",
  "Local RTSP URL",
  "Location",
  "Location precision",
  "Lora bandwidth L1",
  "Lora bandwidth L2",
  "Lora bandwidth L5",
  "MAC address",
  "MCU version",
  "Map area",
  "Minimum firmware",
  "Mission time",
  "Model",
  "Mow progress",
  "Mow schedules",
  "Mow time remaining",
  "Pose East",
  "Pose North",
  "Pose heading",
  "RTK CW interference L1",
  "RTK CW interference L2",
  "RTK CW interference L5",
  "RTK DC voltage L1",
  "RTK DC voltage L2",
  "RTK DC voltage L5",
  "RTK antenna gain L1",
  "RTK antenna gain L2",
  "RTK antenna gain L5",
  "RTK base serial",
  "RTK data error rate",
  "RTK differential age",
  "RTK satellites",
  "RTK status",
  "Registered",
  "Remaining area",
  "Returning for charge",
  "Robot lifted or tilted",
  "Robot state (raw)",
  "Robot timezone",
  "SIM ID",
  "Serial number",
  "Stolen alert",
  "Total map area",
  "Total mapped area",
  "Total mow sessions",
  "Total mow time",
  "Total mowed area (history)",
  "Wheel firmware",
  "Wi-Fi RSSI",
  "Wi-Fi SSID",
  "Wi-Fi link",
  "Wi-Fi signal",
  "Battery",
  "Connectivity",
  "Last mow area",
  "Last mow",
  "RTK base station",
  "Screen PIN",
  "Headlight schedule",
  "Charging",
]);

/** An entity's name without the device prefix, translated unless the user renamed it. */
export function entityLabel(e: HassEntity, device: string, t: T): string {
  const n: string = e.attributes.friendly_name ?? e.entity_id;
  const short = n.startsWith(`${device} `) ? n.slice(device.length + 1) : n;
  return ENTITY_TEXT.has(short) ? t(short) : short;
}
